//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int Id { get; set; }
        public string DoctorFirstName { get; set; }
        public string DoctorLastName { get; set; }
        public string PracticeCity { get; set; }
        public string PracticeZip { get; set; }
        public string PracticePhone { get; set; }
        public int TypeId { get; set; }
    
        public virtual DoctorType DoctorType { get; set; }
    }
}
