//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyLink
    {
        public int Id { get; set; }
        public int InitiatingId { get; set; }
        public int ReceivingProfileId { get; set; }
        public bool IsApproved { get; set; }
        public string RelationshipType { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
